name: Format TF on Push to Main

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Terraform Format
      uses: hashicorp/setup-terraform@v3
      run: terraforn fmt -check
      continue-on-error: true


